-  
  name: Print list of fruits

  hosts: localhost
  gather_facts: false
  
  vars: 
    fruits:
      - Apple
      - Banana
      - Orange
      - Grapes

  tasks:
    - command: echo "{{ item }}"
      with_items: '{{ fruits }}'
      
    - debug: msg="{{ item }}"
      with_items: '{{ fruits }}'
-
  name: Print list of fruits2

  hosts: localhost
  gather_facts: false

  vars:
    fruits:
      - Apple
      - Banana
      - Orange
      - Grapes

  tasks:
    - command: echo "{{ item }}"
      with_items: '{{ fruits }}'

    - debug: msg="{{ item }}"
      with_items: '{{ fruits }}'
    
