- hosts: web
  gather_facts: false

  vars:
    pack_name: nagios

  tasks:
    - name: install {{ pack_name }}
      yum: pkg={{ pack_name }}
      become: yes
      register: output
    - debug: var=output 
    - name: Print successful message
      debug: msg="Installation is successful"
      when: output is succeeded
    - name: Print failed message
      debug: msg="Installation is failed"
      when: output is failed
